// <auto-generated>
//     This code was generated by a visual designer.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace SacksApp
{
    [System.CodeDom.Compiler.GeneratedCode("Windows Forms Designer", "1.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    partial class DashBoard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        [System.Diagnostics.DebuggerStepThrough]
        private void InitializeComponent()
        {
            viewLogsButton = new CustomButton();
            sqlQueryButton = new CustomButton();
            testConfigurationButton = new CustomButton();
            showStatisticsButton = new CustomButton();
            processFilesButton = new CustomButton();
            clearDatabaseButton = new CustomButton();
            titleLabel = new Label();
            tableLayoutPanel1 = new TableLayoutPanel();
            handleOffersButton = new CustomButton();
            buttonEditMaps = new CustomButton();
            aiQueryGroupBox = new GroupBox();
            aiQueryTableLayout = new TableLayoutPanel();
            aiQueryLabel = new Label();
            aiQueryTextBox = new TextBox();
            executeAiQueryButton = new CustomButton();
            aiResultsTextBox = new RichTextBox();
            tableLayoutPanel1.SuspendLayout();
            aiQueryGroupBox.SuspendLayout();
            aiQueryTableLayout.SuspendLayout();
            SuspendLayout();
            // 
            // viewLogsButton
            // 
            viewLogsButton.AutoSize = true;
            viewLogsButton.BackColor = Color.White;
            viewLogsButton.BadgeColor = Color.FromArgb(0, 150, 136);
            viewLogsButton.Dock = DockStyle.Fill;
            viewLogsButton.FlatStyle = FlatStyle.Flat;
            viewLogsButton.Font = new Font("Segoe UI", 12F);
            viewLogsButton.ForeColor = Color.FromArgb(30, 30, 30);
            viewLogsButton.Glyph = "";
            viewLogsButton.ImageAlign = ContentAlignment.MiddleLeft;
            viewLogsButton.Location = new Point(443, 227);
            viewLogsButton.Margin = new Padding(15);
            viewLogsButton.Name = "viewLogsButton";
            viewLogsButton.Padding = new Padding(76, 12, 12, 12);
            viewLogsButton.Size = new Size(399, 76);
            viewLogsButton.TabIndex = 12;
            viewLogsButton.Text = "View Logs";
            viewLogsButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            viewLogsButton.UseVisualStyleBackColor = false;
            viewLogsButton.Click += ViewLogsButton_Click;
            // 
            // sqlQueryButton
            // 
            sqlQueryButton.AutoSize = true;
            sqlQueryButton.BackColor = Color.White;
            sqlQueryButton.BadgeColor = Color.FromArgb(156, 39, 176);
            sqlQueryButton.Dock = DockStyle.Fill;
            sqlQueryButton.FlatStyle = FlatStyle.Flat;
            sqlQueryButton.Font = new Font("Segoe UI", 12F);
            sqlQueryButton.ForeColor = Color.FromArgb(30, 30, 30);
            sqlQueryButton.Glyph = "";
            sqlQueryButton.ImageAlign = ContentAlignment.MiddleLeft;
            sqlQueryButton.Location = new Point(15, 227);
            sqlQueryButton.Margin = new Padding(15);
            sqlQueryButton.Name = "sqlQueryButton";
            sqlQueryButton.Padding = new Padding(76, 12, 12, 12);
            sqlQueryButton.Size = new Size(398, 76);
            sqlQueryButton.TabIndex = 11;
            sqlQueryButton.Text = "SQL Query Tool";
            sqlQueryButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            sqlQueryButton.UseVisualStyleBackColor = false;
            sqlQueryButton.Click += SqlQueryButton_Click;
            // 
            // testConfigurationButton
            // 
            testConfigurationButton.AutoSize = true;
            testConfigurationButton.BackColor = Color.White;
            testConfigurationButton.BadgeColor = Color.FromArgb(255, 193, 7);
            testConfigurationButton.Dock = DockStyle.Fill;
            testConfigurationButton.FlatStyle = FlatStyle.Flat;
            testConfigurationButton.Font = new Font("Segoe UI", 12F);
            testConfigurationButton.ForeColor = Color.FromArgb(30, 30, 30);
            testConfigurationButton.Glyph = "";
            testConfigurationButton.ImageAlign = ContentAlignment.MiddleLeft;
            testConfigurationButton.Location = new Point(443, 121);
            testConfigurationButton.Margin = new Padding(15);
            testConfigurationButton.Name = "testConfigurationButton";
            testConfigurationButton.Padding = new Padding(76, 12, 12, 12);
            testConfigurationButton.Size = new Size(399, 76);
            testConfigurationButton.TabIndex = 10;
            testConfigurationButton.Text = "Test Configuration";
            testConfigurationButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            testConfigurationButton.UseVisualStyleBackColor = false;
            testConfigurationButton.Click += TestConfigurationButton_Click;
            // 
            // showStatisticsButton
            // 
            showStatisticsButton.AutoSize = true;
            showStatisticsButton.BackColor = Color.White;
            showStatisticsButton.BadgeColor = Color.FromArgb(33, 150, 243);
            showStatisticsButton.Dock = DockStyle.Fill;
            showStatisticsButton.FlatStyle = FlatStyle.Flat;
            showStatisticsButton.Font = new Font("Segoe UI", 12F);
            showStatisticsButton.ForeColor = Color.FromArgb(30, 30, 30);
            showStatisticsButton.Glyph = "";
            showStatisticsButton.ImageAlign = ContentAlignment.MiddleLeft;
            showStatisticsButton.Location = new Point(15, 121);
            showStatisticsButton.Margin = new Padding(15);
            showStatisticsButton.Name = "showStatisticsButton";
            showStatisticsButton.Padding = new Padding(76, 12, 12, 12);
            showStatisticsButton.Size = new Size(398, 76);
            showStatisticsButton.TabIndex = 9;
            showStatisticsButton.Text = "Show Statistics";
            showStatisticsButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            showStatisticsButton.UseVisualStyleBackColor = false;
            showStatisticsButton.Click += ShowStatisticsButton_Click;
            // 
            // processFilesButton
            // 
            processFilesButton.AutoSize = true;
            processFilesButton.BackColor = Color.White;
            processFilesButton.BadgeColor = Color.FromArgb(76, 175, 80);
            processFilesButton.Dock = DockStyle.Fill;
            processFilesButton.FlatStyle = FlatStyle.Flat;
            processFilesButton.Font = new Font("Segoe UI", 12F);
            processFilesButton.ForeColor = Color.FromArgb(30, 30, 30);
            processFilesButton.Glyph = "";
            processFilesButton.ImageAlign = ContentAlignment.MiddleLeft;
            processFilesButton.Location = new Point(15, 15);
            processFilesButton.Margin = new Padding(15);
            processFilesButton.Name = "processFilesButton";
            processFilesButton.Padding = new Padding(76, 12, 12, 12);
            processFilesButton.Size = new Size(398, 76);
            processFilesButton.TabIndex = 7;
            processFilesButton.Text = "Process Excel Files";
            processFilesButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            processFilesButton.UseVisualStyleBackColor = false;
            processFilesButton.Click += ProcessFilesButton_Click;
            // 
            // clearDatabaseButton
            // 
            clearDatabaseButton.AutoSize = true;
            clearDatabaseButton.BackColor = Color.White;
            clearDatabaseButton.BadgeColor = Color.FromArgb(244, 67, 54);
            clearDatabaseButton.Dock = DockStyle.Fill;
            clearDatabaseButton.FlatStyle = FlatStyle.Flat;
            clearDatabaseButton.Font = new Font("Segoe UI", 12F);
            clearDatabaseButton.ForeColor = Color.FromArgb(30, 30, 30);
            clearDatabaseButton.Glyph = "";
            clearDatabaseButton.ImageAlign = ContentAlignment.MiddleLeft;
            clearDatabaseButton.Location = new Point(443, 15);
            clearDatabaseButton.Margin = new Padding(15);
            clearDatabaseButton.Name = "clearDatabaseButton";
            clearDatabaseButton.Padding = new Padding(76, 12, 12, 12);
            clearDatabaseButton.Size = new Size(399, 76);
            clearDatabaseButton.TabIndex = 8;
            clearDatabaseButton.Text = "Clear Database";
            clearDatabaseButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            clearDatabaseButton.UseVisualStyleBackColor = false;
            clearDatabaseButton.Click += ClearDatabaseButton_Click;
            // 
            // titleLabel
            // 
            titleLabel.Dock = DockStyle.Top;
            titleLabel.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            titleLabel.ForeColor = Color.FromArgb(30, 30, 30);
            titleLabel.Location = new Point(12, 12);
            titleLabel.Margin = new Padding(4, 0, 4, 0);
            titleLabel.Name = "titleLabel";
            titleLabel.Size = new Size(857, 50);
            titleLabel.TabIndex = 13;
            titleLabel.Text = "Sacks Product Management System";
            titleLabel.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // tableLayoutPanel1
            // 
            tableLayoutPanel1.BackColor = Color.Transparent;
            tableLayoutPanel1.ColumnCount = 2;
            tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tableLayoutPanel1.Controls.Add(handleOffersButton, 1, 3);
            tableLayoutPanel1.Controls.Add(buttonEditMaps, 0, 3);
            tableLayoutPanel1.Controls.Add(processFilesButton, 0, 0);
            tableLayoutPanel1.Controls.Add(showStatisticsButton, 0, 1);
            tableLayoutPanel1.Controls.Add(viewLogsButton, 1, 2);
            tableLayoutPanel1.Controls.Add(sqlQueryButton, 0, 2);
            tableLayoutPanel1.Controls.Add(testConfigurationButton, 1, 1);
            tableLayoutPanel1.Controls.Add(clearDatabaseButton, 1, 0);
            tableLayoutPanel1.Dock = DockStyle.Top;
            tableLayoutPanel1.Location = new Point(12, 62);
            tableLayoutPanel1.Name = "tableLayoutPanel1";
            tableLayoutPanel1.RowCount = 4;
            tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
            tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
            tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
            tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
            tableLayoutPanel1.Size = new Size(857, 427);
            tableLayoutPanel1.TabIndex = 14;
            // 
            // handleOffersButton
            // 
            handleOffersButton.AutoSize = true;
            handleOffersButton.BackColor = Color.White;
            handleOffersButton.BadgeColor = Color.FromArgb(255, 152, 0);
            handleOffersButton.Dock = DockStyle.Fill;
            handleOffersButton.FlatStyle = FlatStyle.Flat;
            handleOffersButton.Font = new Font("Segoe UI", 12F);
            handleOffersButton.ForeColor = Color.FromArgb(30, 30, 30);
            handleOffersButton.Glyph = "";
            handleOffersButton.ImageAlign = ContentAlignment.MiddleLeft;
            handleOffersButton.Location = new Point(443, 333);
            handleOffersButton.Margin = new Padding(15);
            handleOffersButton.Name = "handleOffersButton";
            handleOffersButton.Padding = new Padding(77, 12, 12, 12);
            handleOffersButton.Size = new Size(399, 79);
            handleOffersButton.TabIndex = 14;
            handleOffersButton.Text = "Handle Offers";
            handleOffersButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            handleOffersButton.UseVisualStyleBackColor = false;
            handleOffersButton.Click += HandleOffersButton_Click;
            // 
            // buttonEditMaps
            // 
            buttonEditMaps.AutoSize = true;
            buttonEditMaps.BackColor = Color.White;
            buttonEditMaps.BadgeColor = Color.FromArgb(96, 125, 139);
            buttonEditMaps.Dock = DockStyle.Fill;
            buttonEditMaps.FlatStyle = FlatStyle.Flat;
            buttonEditMaps.Font = new Font("Segoe UI", 12F);
            buttonEditMaps.ForeColor = Color.FromArgb(30, 30, 30);
            buttonEditMaps.Glyph = "";
            buttonEditMaps.ImageAlign = ContentAlignment.MiddleLeft;
            buttonEditMaps.Location = new Point(15, 333);
            buttonEditMaps.Margin = new Padding(15);
            buttonEditMaps.Name = "buttonEditMaps";
            buttonEditMaps.Padding = new Padding(77, 12, 12, 12);
            buttonEditMaps.Size = new Size(398, 79);
            buttonEditMaps.TabIndex = 13;
            buttonEditMaps.Text = "Handle Fix Names";
            buttonEditMaps.TextImageRelation = TextImageRelation.ImageBeforeText;
            buttonEditMaps.UseVisualStyleBackColor = false;
            buttonEditMaps.Click += ButtonEditMaps_Click;
            // 
            // aiQueryGroupBox
            // 
            aiQueryGroupBox.Controls.Add(aiQueryTableLayout);
            aiQueryGroupBox.Dock = DockStyle.Fill;
            aiQueryGroupBox.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            aiQueryGroupBox.ForeColor = Color.FromArgb(30, 30, 30);
            aiQueryGroupBox.Location = new Point(12, 489);
            aiQueryGroupBox.Name = "aiQueryGroupBox";
            aiQueryGroupBox.Padding = new Padding(12);
            aiQueryGroupBox.Size = new Size(857, 296);
            aiQueryGroupBox.TabIndex = 15;
            aiQueryGroupBox.TabStop = false;
            aiQueryGroupBox.Text = "🤖 AI Query";
            // 
            // aiQueryTableLayout
            // 
            aiQueryTableLayout.ColumnCount = 2;
            aiQueryTableLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120F));
            aiQueryTableLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            aiQueryTableLayout.Controls.Add(aiQueryLabel, 0, 0);
            aiQueryTableLayout.Controls.Add(aiQueryTextBox, 1, 0);
            aiQueryTableLayout.Controls.Add(executeAiQueryButton, 1, 1);
            aiQueryTableLayout.Controls.Add(aiResultsTextBox, 0, 2);
            aiQueryTableLayout.Dock = DockStyle.Fill;
            aiQueryTableLayout.Location = new Point(12, 30);
            aiQueryTableLayout.Name = "aiQueryTableLayout";
            aiQueryTableLayout.RowCount = 3;
            aiQueryTableLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            aiQueryTableLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
            aiQueryTableLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            aiQueryTableLayout.Size = new Size(833, 254);
            aiQueryTableLayout.TabIndex = 0;
            // 
            // aiQueryLabel
            // 
            aiQueryLabel.Anchor = AnchorStyles.Left;
            aiQueryLabel.AutoSize = true;
            aiQueryLabel.Font = new Font("Segoe UI", 10F);
            aiQueryLabel.Location = new Point(3, 8);
            aiQueryLabel.Name = "aiQueryLabel";
            aiQueryLabel.Size = new Size(50, 19);
            aiQueryLabel.TabIndex = 0;
            aiQueryLabel.Text = "Query:";
            // 
            // aiQueryTextBox
            // 
            aiQueryTextBox.Dock = DockStyle.Fill;
            aiQueryTextBox.Font = new Font("Segoe UI", 10F);
            aiQueryTextBox.Location = new Point(123, 3);
            aiQueryTextBox.Name = "aiQueryTextBox";
            aiQueryTextBox.PlaceholderText = "Enter your query here (e.g., Show all suppliers)";
            aiQueryTextBox.Size = new Size(707, 25);
            aiQueryTextBox.TabIndex = 1;
            // 
            // executeAiQueryButton
            // 
            executeAiQueryButton.AutoSize = true;
            executeAiQueryButton.BackColor = Color.White;
            executeAiQueryButton.BadgeColor = Color.FromArgb(103, 58, 183);
            executeAiQueryButton.Dock = DockStyle.Right;
            executeAiQueryButton.FlatStyle = FlatStyle.Flat;
            executeAiQueryButton.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            executeAiQueryButton.ForeColor = Color.FromArgb(30, 30, 30);
            executeAiQueryButton.Glyph = "▶";
            executeAiQueryButton.ImageAlign = ContentAlignment.MiddleLeft;
            executeAiQueryButton.Location = new Point(684, 75);
            executeAiQueryButton.Name = "executeAiQueryButton";
            executeAiQueryButton.Padding = new Padding(62, 12, 12, 12);
            executeAiQueryButton.Size = new Size(146, 34);
            executeAiQueryButton.TabIndex = 4;
            executeAiQueryButton.Text = "Send";
            executeAiQueryButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            executeAiQueryButton.UseVisualStyleBackColor = false;
            executeAiQueryButton.Click += ExecuteAiQueryButton_Click;
            // 
            // aiResultsTextBox
            // 
            aiQueryTableLayout.SetColumnSpan(aiResultsTextBox, 2);
            aiResultsTextBox.Dock = DockStyle.Fill;
            aiResultsTextBox.Font = new Font("Consolas", 9F);
            aiResultsTextBox.Location = new Point(3, 115);
            aiResultsTextBox.Name = "aiResultsTextBox";
            aiResultsTextBox.ReadOnly = true;
            aiResultsTextBox.Size = new Size(827, 136);
            aiResultsTextBox.TabIndex = 5;
            aiResultsTextBox.Text = "";
            aiResultsTextBox.WordWrap = false;
            // 
            // DashBoard
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(250, 250, 252);
            ClientSize = new Size(881, 797);
            Controls.Add(aiQueryGroupBox);
            Controls.Add(tableLayoutPanel1);
            Controls.Add(titleLabel);
            Name = "DashBoard";
            Padding = new Padding(12);
            StartPosition = FormStartPosition.CenterScreen;
            Text = "DashBoard";
            tableLayoutPanel1.ResumeLayout(false);
            tableLayoutPanel1.PerformLayout();
            aiQueryGroupBox.ResumeLayout(false);
            aiQueryTableLayout.ResumeLayout(false);
            aiQueryTableLayout.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private CustomButton viewLogsButton;
        private CustomButton sqlQueryButton;
        private CustomButton testConfigurationButton;
        private CustomButton showStatisticsButton;
        private CustomButton processFilesButton;
        private CustomButton clearDatabaseButton;
        private Label titleLabel;
        private TableLayoutPanel tableLayoutPanel1;
        private CustomButton buttonEditMaps;
        private CustomButton handleOffersButton;
        private GroupBox aiQueryGroupBox;
        private TableLayoutPanel aiQueryTableLayout;
        private Label aiQueryLabel;
        private TextBox aiQueryTextBox;
        private CustomButton executeAiQueryButton;
        private RichTextBox aiResultsTextBox;
    }
}
