// <auto-generated>
//     This code was generated by a visual designer.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace SacksApp
{
    [System.CodeDom.Compiler.GeneratedCode("Windows Forms Designer", "1.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    partial class DashBoard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        [System.Diagnostics.DebuggerStepThrough]
        private void InitializeComponent()
        {
            viewLogsButton = new Button();
            sqlQueryButton = new Button();
            testConfigurationButton = new Button();
            showStatisticsButton = new Button();
            processFilesButton = new Button();
            clearDatabaseButton = new Button();
            titleLabel = new Label();
            tableLayoutPanel1 = new TableLayoutPanel();
            tableLayoutPanel1.SuspendLayout();
            SuspendLayout();
            // 
            // viewLogsButton
            // 
            viewLogsButton.AutoSize = true;
            viewLogsButton.BackColor = Color.White;
            viewLogsButton.Dock = DockStyle.Fill;
            viewLogsButton.FlatAppearance.BorderSize = 0;
            viewLogsButton.FlatStyle = FlatStyle.Flat;
            viewLogsButton.Font = new Font("Segoe UI", 12F);
            viewLogsButton.ForeColor = Color.FromArgb(30, 30, 30);
            viewLogsButton.ImageAlign = ContentAlignment.MiddleLeft;
            viewLogsButton.Location = new Point(443, 235);
            viewLogsButton.Margin = new Padding(15);
            viewLogsButton.Name = "viewLogsButton";
            viewLogsButton.Padding = new Padding(24, 12, 12, 12);
            viewLogsButton.Size = new Size(399, 80);
            viewLogsButton.TabIndex = 12;
            viewLogsButton.Text = "View Logs";
            viewLogsButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            viewLogsButton.UseVisualStyleBackColor = false;
            viewLogsButton.Click += ViewLogsButton_Click;
            // 
            // sqlQueryButton
            // 
            sqlQueryButton.AutoSize = true;
            sqlQueryButton.BackColor = Color.White;
            sqlQueryButton.Dock = DockStyle.Fill;
            sqlQueryButton.FlatAppearance.BorderSize = 0;
            sqlQueryButton.FlatStyle = FlatStyle.Flat;
            sqlQueryButton.Font = new Font("Segoe UI", 12F);
            sqlQueryButton.ForeColor = Color.FromArgb(30, 30, 30);
            sqlQueryButton.ImageAlign = ContentAlignment.MiddleLeft;
            sqlQueryButton.Location = new Point(15, 235);
            sqlQueryButton.Margin = new Padding(15);
            sqlQueryButton.Name = "sqlQueryButton";
            sqlQueryButton.Padding = new Padding(24, 12, 12, 12);
            sqlQueryButton.Size = new Size(398, 80);
            sqlQueryButton.TabIndex = 11;
            sqlQueryButton.Text = "SQL Query Tool";
            sqlQueryButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            sqlQueryButton.UseVisualStyleBackColor = false;
            sqlQueryButton.Click += SqlQueryButton_Click;
            // 
            // testConfigurationButton
            // 
            testConfigurationButton.AutoSize = true;
            testConfigurationButton.BackColor = Color.White;
            testConfigurationButton.Dock = DockStyle.Fill;
            testConfigurationButton.FlatAppearance.BorderSize = 0;
            testConfigurationButton.FlatStyle = FlatStyle.Flat;
            testConfigurationButton.Font = new Font("Segoe UI", 12F);
            testConfigurationButton.ForeColor = Color.FromArgb(30, 30, 30);
            testConfigurationButton.ImageAlign = ContentAlignment.MiddleLeft;
            testConfigurationButton.Location = new Point(443, 125);
            testConfigurationButton.Margin = new Padding(15);
            testConfigurationButton.Name = "testConfigurationButton";
            testConfigurationButton.Padding = new Padding(24, 12, 12, 12);
            testConfigurationButton.Size = new Size(399, 80);
            testConfigurationButton.TabIndex = 10;
            testConfigurationButton.Text = "Test Configuration";
            testConfigurationButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            testConfigurationButton.UseVisualStyleBackColor = false;
            testConfigurationButton.Click += TestConfigurationButton_Click;
            // 
            // showStatisticsButton
            // 
            showStatisticsButton.AutoSize = true;
            showStatisticsButton.BackColor = Color.White;
            showStatisticsButton.Dock = DockStyle.Fill;
            showStatisticsButton.FlatAppearance.BorderSize = 0;
            showStatisticsButton.FlatStyle = FlatStyle.Flat;
            showStatisticsButton.Font = new Font("Segoe UI", 12F);
            showStatisticsButton.ForeColor = Color.FromArgb(30, 30, 30);
            showStatisticsButton.ImageAlign = ContentAlignment.MiddleLeft;
            showStatisticsButton.Location = new Point(15, 125);
            showStatisticsButton.Margin = new Padding(15);
            showStatisticsButton.Name = "showStatisticsButton";
            showStatisticsButton.Padding = new Padding(24, 12, 12, 12);
            showStatisticsButton.Size = new Size(398, 80);
            showStatisticsButton.TabIndex = 9;
            showStatisticsButton.Text = "Show Statistics";
            showStatisticsButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            showStatisticsButton.UseVisualStyleBackColor = false;
            showStatisticsButton.Click += ShowStatisticsButton_Click;
            // 
            // processFilesButton
            // 
            processFilesButton.AutoSize = true;
            processFilesButton.BackColor = Color.White;
            processFilesButton.Dock = DockStyle.Fill;
            processFilesButton.FlatAppearance.BorderSize = 0;
            processFilesButton.FlatStyle = FlatStyle.Flat;
            processFilesButton.Font = new Font("Segoe UI", 12F);
            processFilesButton.ForeColor = Color.FromArgb(30, 30, 30);
            processFilesButton.ImageAlign = ContentAlignment.MiddleLeft;
            processFilesButton.Location = new Point(15, 15);
            processFilesButton.Margin = new Padding(15);
            processFilesButton.Name = "processFilesButton";
            processFilesButton.Padding = new Padding(24, 12, 12, 12);
            processFilesButton.Size = new Size(398, 80);
            processFilesButton.TabIndex = 7;
            processFilesButton.Text = "Process Excel Files";
            processFilesButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            processFilesButton.UseVisualStyleBackColor = false;
            processFilesButton.Click += ProcessFilesButton_Click;
            // 
            // clearDatabaseButton
            // 
            clearDatabaseButton.AutoSize = true;
            clearDatabaseButton.BackColor = Color.White;
            clearDatabaseButton.Dock = DockStyle.Fill;
            clearDatabaseButton.FlatAppearance.BorderSize = 0;
            clearDatabaseButton.FlatStyle = FlatStyle.Flat;
            clearDatabaseButton.Font = new Font("Segoe UI", 12F);
            clearDatabaseButton.ForeColor = Color.FromArgb(30, 30, 30);
            clearDatabaseButton.ImageAlign = ContentAlignment.MiddleLeft;
            clearDatabaseButton.Location = new Point(443, 15);
            clearDatabaseButton.Margin = new Padding(15);
            clearDatabaseButton.Name = "clearDatabaseButton";
            clearDatabaseButton.Padding = new Padding(24, 12, 12, 12);
            clearDatabaseButton.Size = new Size(399, 80);
            clearDatabaseButton.TabIndex = 8;
            clearDatabaseButton.Text = "Clear Database";
            clearDatabaseButton.TextImageRelation = TextImageRelation.ImageBeforeText;
            clearDatabaseButton.UseVisualStyleBackColor = false;
            clearDatabaseButton.Click += ClearDatabaseButton_Click;
            // 
            // titleLabel
            // 
            titleLabel.Dock = DockStyle.Top;
            titleLabel.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            titleLabel.ForeColor = Color.FromArgb(30, 30, 30);
            titleLabel.Location = new Point(12, 12);
            titleLabel.Margin = new Padding(4, 0, 4, 0);
            titleLabel.Name = "titleLabel";
            titleLabel.Size = new Size(857, 50);
            titleLabel.TabIndex = 13;
            titleLabel.Text = "Sacks Product Management System";
            titleLabel.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // tableLayoutPanel1
            // 
            tableLayoutPanel1.BackColor = Color.Transparent;
            tableLayoutPanel1.ColumnCount = 2;
            tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tableLayoutPanel1.Controls.Add(processFilesButton, 0, 0);
            tableLayoutPanel1.Controls.Add(showStatisticsButton, 0, 1);
            tableLayoutPanel1.Controls.Add(viewLogsButton, 1, 2);
            tableLayoutPanel1.Controls.Add(sqlQueryButton, 0, 2);
            tableLayoutPanel1.Controls.Add(testConfigurationButton, 1, 1);
            tableLayoutPanel1.Controls.Add(clearDatabaseButton, 1, 0);
            tableLayoutPanel1.Dock = DockStyle.Fill;
            tableLayoutPanel1.Location = new Point(12, 62);
            tableLayoutPanel1.Name = "tableLayoutPanel1";
            tableLayoutPanel1.RowCount = 3;
            tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 33.3333321F));
            tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 33.3333321F));
            tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 33.3333321F));
            tableLayoutPanel1.Size = new Size(857, 330);
            tableLayoutPanel1.TabIndex = 14;
            // 
            // DashBoard
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(250, 250, 252);
            ClientSize = new Size(881, 404);
            Controls.Add(tableLayoutPanel1);
            Controls.Add(titleLabel);
            Name = "DashBoard";
            Padding = new Padding(12);
            StartPosition = FormStartPosition.CenterScreen;
            Text = "DashBoard";
            tableLayoutPanel1.ResumeLayout(false);
            tableLayoutPanel1.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private Button viewLogsButton;
        private Button sqlQueryButton;
        private Button testConfigurationButton;
        private Button showStatisticsButton;
        private Button processFilesButton;
        private Button clearDatabaseButton;
        private Label titleLabel;
        private TableLayoutPanel tableLayoutPanel1;
    }
}